/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AprovacoesRouteImport } from './routes/aprovacoes'
import { Route as AtivosRouteImport } from './routes/ativos'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SoftwaresRouteImport } from './routes/softwares'
import { Route as VulnerabilidadesRouteImport } from './routes/vulnerabilidades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacoesRoute = AprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivosRoute = AtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwaresRoute = SoftwaresRouteImport.update({
  id: '/softwares',
  path: '/softwares',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerabilidadesRoute = VulnerabilidadesRouteImport.update({
  id: '/vulnerabilidades',
  path: '/vulnerabilidades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/ativos': typeof AtivosRoute
  '/automacoes': typeof AutomacoesRoute
  '/catalogo': typeof CatalogoRoute
  '/chamados': typeof ChamadosRoute
  '/historico': typeof HistoricoRoute
  '/relatorios': typeof RelatoriosRoute
  '/softwares': typeof SoftwaresRoute
  '/vulnerabilidades': typeof VulnerabilidadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/ativos': typeof AtivosRoute
  '/automacoes': typeof AutomacoesRoute
  '/catalogo': typeof CatalogoRoute
  '/chamados': typeof ChamadosRoute
  '/historico': typeof HistoricoRoute
  '/relatorios': typeof RelatoriosRoute
  '/softwares': typeof SoftwaresRoute
  '/vulnerabilidades': typeof VulnerabilidadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/ativos': typeof AtivosRoute
  '/automacoes': typeof AutomacoesRoute
  '/catalogo': typeof CatalogoRoute
  '/chamados': typeof ChamadosRoute
  '/historico': typeof HistoricoRoute
  '/relatorios': typeof RelatoriosRoute
  '/softwares': typeof SoftwaresRoute
  '/vulnerabilidades': typeof VulnerabilidadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/aprovacoes'
    | '/ativos'
    | '/automacoes'
    | '/catalogo'
    | '/chamados'
    | '/historico'
    | '/relatorios'
    | '/softwares'
    | '/vulnerabilidades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/aprovacoes'
    | '/ativos'
    | '/automacoes'
    | '/catalogo'
    | '/chamados'
    | '/historico'
    | '/relatorios'
    | '/softwares'
    | '/vulnerabilidades'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/aprovacoes'
    | '/ativos'
    | '/automacoes'
    | '/catalogo'
    | '/chamados'
    | '/historico'
    | '/relatorios'
    | '/softwares'
    | '/vulnerabilidades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AprovacoesRoute: typeof AprovacoesRoute
  AtivosRoute: typeof AtivosRoute
  AutomacoesRoute: typeof AutomacoesRoute
  CatalogoRoute: typeof CatalogoRoute
  ChamadosRoute: typeof ChamadosRoute
  HistoricoRoute: typeof HistoricoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SoftwaresRoute: typeof SoftwaresRoute
  VulnerabilidadesRoute: typeof VulnerabilidadesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacoes': {
      id: '/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AprovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativos': {
      id: '/ativos'
      path: '/ativos'
      fullPath: '/ativos'
      preLoaderRoute: typeof AtivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/softwares': {
      id: '/softwares'
      path: '/softwares'
      fullPath: '/softwares'
      preLoaderRoute: typeof SoftwaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerabilidades': {
      id: '/vulnerabilidades'
      path: '/vulnerabilidades'
      fullPath: '/vulnerabilidades'
      preLoaderRoute: typeof VulnerabilidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AprovacoesRoute: AprovacoesRoute,
  AtivosRoute: AtivosRoute,
  AutomacoesRoute: AutomacoesRoute,
  CatalogoRoute: CatalogoRoute,
  ChamadosRoute: ChamadosRoute,
  HistoricoRoute: HistoricoRoute,
  RelatoriosRoute: RelatoriosRoute,
  SoftwaresRoute: SoftwaresRoute,
  VulnerabilidadesRoute: VulnerabilidadesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
